CREATE TABLE [dbo].[User]
(
	UserId INT NOT NULL IDENTITY,
	LastName NVARCHAR(75) NOT NULL,
	FirstName NVARCHAR(75) NOT NULL,
	Email NVARCHAR(384) NOT NULL,
	Passwd VARBINARY(64) NOT NULL,
	IsAdmin BIT NOT NULL
		CONSTRAINT DF_User_Admin DEFAULT (0),
	IsActive BIT NOT NULL
		CONSTRAINT DF_User_Active DEFAULT (1),
	CONSTRAINT [PK_User] PRIMARY KEY ([UserId]),
	CONSTRAINT [UK_User_Email] UNIQUE (Email)

)
